name: Norm
on:
  push:
    branches: [ "main", "5-actions" ]
  pull_request:
    branches: [ "main", "5-actions" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Norminette.
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette
      - name: Norm check.
        run: python3 .github/sh/norm.py